# **Classifying movie reviews** as positive or negative (binary classification)


In [4]:
import tensorflow as tf 

In [5]:
from tensorflow.keras.datasets import imdb

In [6]:
(train_data, train_lables),(test_data, test_lables) = imdb.load_data( num_words=10000)

<string>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/datasets/imdb.py:159: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/datasets/imdb.py:160: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 

In [7]:
# train_data[0]

In [8]:
from tensorflow.keras.utils import to_categorical

In [9]:
# train_data = to_categorical(train_data)
# test_data = to_categorical(test_data)

In [10]:
import numpy as np
def vectorize_sequences(sequences, dimension=10000):
  results = np.zeros((len(sequences), dimension))
  for i, sequence in enumerate(sequences):
    results[i, sequence] = 1.
  return results
x_train = vectorize_sequences(train_data)
x_test = vectorize_sequences(test_data)

In [11]:
y_train = np.asarray(train_lables).astype('float32')

In [12]:
y_test = np.asarray(test_lables).astype('float32')

In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers

In [14]:
network = Sequential()

In [15]:
network.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
network.add(layers.Dense(16, activation='relu'))
network.add(layers.Dense(1, activation='sigmoid'))

In [16]:
network.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics='accuracy')

# create a validation set

In [17]:
x_val = x_train[:10000]

In [18]:
y_val = y_train[:10000]

In [19]:
history = network.fit(x_train, y_train, epochs=20, batch_size=500, validation_data=(x_val, y_val))

Epoch 1/20
50/50 [==============================] - 3s 45ms/step - loss: 0.5524 - accuracy: 0.7241 - val_loss: 0.2848 - val_accuracy: 0.9093
Epoch 2/20
50/50 [==============================] - 2s 32ms/step - loss: 0.2726 - accuracy: 0.9082 - val_loss: 0.1955 - val_accuracy: 0.9397
Epoch 3/20
50/50 [==============================] - 2s 32ms/step - loss: 0.1968 - accuracy: 0.9308 - val_loss: 0.1624 - val_accuracy: 0.9475
Epoch 4/20
50/50 [==============================] - 2s 34ms/step - loss: 0.1677 - accuracy: 0.9418 - val_loss: 0.1349 - val_accuracy: 0.9583
Epoch 5/20
50/50 [==============================] - 2s 33ms/step - loss: 0.1402 - accuracy: 0.9527 - val_loss: 0.1158 - val_accuracy: 0.9655
Epoch 6/20
50/50 [==============================] - 2s 33ms/step - loss: 0.1164 - accuracy: 0.9604 - val_loss: 0.1011 - val_accuracy: 0.9700
Epoch 7/20
50/50 [==============================] - 2s 32ms/step - loss: 0.1058 - accuracy: 0.9656 - val_loss: 0.0894 - val_accuracy: 0.9730
Epoch 8/20
50

In [20]:
history_dict = history.history

In [21]:
history_dict.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [22]:
model = Sequential()
model.add(layers.Dense(40, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(20, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [23]:
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics='accuracy')

In [24]:
model.fit(x_train, y_train, epochs=15, batch_size=512)

Epoch 1/15
49/49 [==============================] - 3s 41ms/step - loss: 0.5243 - accuracy: 0.7439
Epoch 2/15
49/49 [==============================] - 2s 41ms/step - loss: 0.2442 - accuracy: 0.9129
Epoch 3/15
49/49 [==============================] - 2s 38ms/step - loss: 0.1836 - accuracy: 0.9347
Epoch 4/15
49/49 [==============================] - 2s 37ms/step - loss: 0.1546 - accuracy: 0.9474
Epoch 5/15
49/49 [==============================] - 2s 37ms/step - loss: 0.1211 - accuracy: 0.9575
Epoch 6/15
49/49 [==============================] - 2s 37ms/step - loss: 0.1049 - accuracy: 0.9641
Epoch 7/15
49/49 [==============================] - 2s 38ms/step - loss: 0.0878 - accuracy: 0.9704
Epoch 8/15
49/49 [==============================] - 2s 37ms/step - loss: 0.0785 - accuracy: 0.9749
Epoch 9/15
49/49 [==============================] - 2s 37ms/step - loss: 0.0623 - accuracy: 0.9808
Epoch 10/15
49/49 [==============================] - 2s 38ms/step - loss: 0.0502 - accuracy: 0.9850
Epoch 11/

In [25]:
model.evaluate(x_test, y_test)

782/782 [==============================] - 2s 2ms/step - loss: 0.7226 - accuracy: 0.8562


[0.7226449251174927, 0.8562399744987488]

In [26]:
model.predict(x_test)

array([[0.0090003 ],
       [0.99999964],
       [0.8925364 ],
       ...,
       [0.01305211],
       [0.0047794 ],
       [0.99440515]], dtype=float32)

In [27]:
model1 = Sequential()
model1.add(layers.Dense(100, activation='relu', input_shape=(10000,)))
model1.add(layers.Dense(60, activation='relu'))
model1.add(layers.Dense(20, activation='relu'))
model1.add(layers.Dense(1, activation='sigmoid'))

In [28]:
model1.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics='accuracy')

In [29]:
model1.fit(x_train, y_train, epochs=10, batch_size=400)

Epoch 1/10
63/63 [==============================] - 4s 55ms/step - loss: 0.5217 - accuracy: 0.7347
Epoch 2/10
63/63 [==============================] - 4s 60ms/step - loss: 0.2247 - accuracy: 0.9122
Epoch 3/10
63/63 [==============================] - 4s 56ms/step - loss: 0.1628 - accuracy: 0.9393
Epoch 4/10
63/63 [==============================] - 4s 56ms/step - loss: 0.1123 - accuracy: 0.9589
Epoch 5/10
63/63 [==============================] - 3s 55ms/step - loss: 0.0838 - accuracy: 0.9688
Epoch 6/10
63/63 [==============================] - 3s 54ms/step - loss: 0.0331 - accuracy: 0.9896
Epoch 7/10
63/63 [==============================] - 3s 55ms/step - loss: 0.0318 - accuracy: 0.9910
Epoch 8/10
63/63 [==============================] - 4s 58ms/step - loss: 0.0186 - accuracy: 0.9956
Epoch 9/10
63/63 [==============================] - 3s 55ms/step - loss: 0.0090 - accuracy: 0.9982
Epoch 10/10
63/63 [==============================] - 3s 55ms/step - loss: 0.0011 - accuracy: 0.9998


In [30]:
model1.predict(x_test)

array([[8.614063e-04],
       [1.000000e+00],
       [1.000000e+00],
       ...,
       [9.734988e-03],
       [4.686177e-03],
       [9.988995e-01]], dtype=float32)

In [31]:
model1.evaluate(x_test, y_test)

782/782 [==============================] - 3s 3ms/step - loss: 0.9257 - accuracy: 0.8655


[0.9256958365440369, 0.8655200004577637]

In [37]:
models = Sequential()
models.add(layers.Dense(500, activation='tanh', input_shape=(10000,)))
models.add(layers.Dense(300, activation='tanh'))
models.add(layers.Dense(200, activation='tanh'))
models.add(layers.Dense(100, activation='tanh'))
models.add(layers.Dense(1, activation='sigmoid'))

In [38]:
models.compile(optimizer='rmsprop', loss='mse', metrics='accuracy' )

In [39]:
models.fit(x_train, y_train, epochs=10, batch_size=300, validation_data=(x_val, y_val))

Epoch 1/10
84/84 [==============================] - 17s 189ms/step - loss: 0.2266 - accuracy: 0.6723 - val_loss: 0.0574 - val_accuracy: 0.9326
Epoch 2/10
84/84 [==============================] - 15s 184ms/step - loss: 0.0685 - accuracy: 0.9100 - val_loss: 0.0485 - val_accuracy: 0.9422
Epoch 3/10
84/84 [==============================] - 16s 188ms/step - loss: 0.0491 - accuracy: 0.9360 - val_loss: 0.0369 - val_accuracy: 0.9583
Epoch 4/10
84/84 [==============================] - 15s 183ms/step - loss: 0.0395 - accuracy: 0.9519 - val_loss: 0.0279 - val_accuracy: 0.9671
Epoch 5/10
84/84 [==============================] - 15s 184ms/step - loss: 0.0320 - accuracy: 0.9606 - val_loss: 0.0207 - val_accuracy: 0.9763
Epoch 6/10
84/84 [==============================] - 16s 186ms/step - loss: 0.0246 - accuracy: 0.9702 - val_loss: 0.0209 - val_accuracy: 0.9747
Epoch 7/10
84/84 [==============================] - 15s 183ms/step - loss: 0.0175 - accuracy: 0.9794 - val_loss: 0.0122 - val_accuracy: 0.9864

In [40]:
models.evaluate(x_test, y_test)

782/782 [==============================] - 10s 13ms/step - loss: 0.1175 - accuracy: 0.8652


[0.11753522604703903, 0.8652399778366089]

In [41]:
models.predict(x_test)

array([[0.0031105 ],
       [0.99817306],
       [0.947371  ],
       ...,
       [0.01500377],
       [0.00804013],
       [0.58266836]], dtype=float32)